#!/usr/bin/env bash

UNAME=`uname`;
VERSION="07-20"

echo "Swift 3 Installer ($VERSION)";

if [[ $UNAME == "Darwin" ]];
then
    OS="macos";
    SWIFTV_EXPECTED="888ff1ae99";
else
    if [[ $UNAME == "Linux" ]];
    then
        SWIFTV_EXPECTED="55bf02ec04";
        UBUNTU_RELEASE=`lsb_release -a 2>/dev/null`;
        if [[ $UBUNTU_RELEASE == *"15.10"* ]];
        then
            OS="ubuntu1510";
        else
            OS="ubuntu1404";
        fi
    else
        echo "Unsupported Operating System: $UNAME";
    fi
fi

if [[ $TRAVIS ]];
then
    git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv
    export SWIFTENV_ROOT="$HOME/.swiftenv"
    export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
    swiftenv rehash
    which swift
    echo $PATH
    swiftenv
fi

if [[ `which swift` != *"swiftenv"* ]];
then
    echo "❌  Swiftenv is not installed."
    echo ""
    echo "Full installation instructions:"
    echo "    https://swiftenv.fuller.li/en/latest/installation.html"
    echo ""
    echo "Via Git:"
    echo "    git clone https://github.com/kylef/swiftenv.git ~/.swiftenv"
    echo "Add to your Bash profile:"
    echo "    export SWIFTENV_ROOT=\"\$HOME/.swiftenv\""
    echo "    export PATH=\"\$SWIFTENV_ROOT/bin:\$PATH\""
    echo "    eval \"\$(swiftenv init -)\""
    if [[ $OS == "macos" ]];
    then
        echo ""
        echo "Via Homebrew:"
        echo "    brew install kylef/formulae/swiftenv"
        echo "Add to your Bash Profile:"
        echo "    if which swiftenv > /dev/null; then eval \"\$(swiftenv init -)\"; fi"
    fi
    exit 1
fi

echo "🖥  Operating System: $OS";

NAME="swift-DEVELOPMENT-SNAPSHOT-2016-$VERSION-qutheory"
if [[ $OS == "macos" ]];
then
    INSTALL_LOC="/Library/Developer/Toolchains";
    TOOLCHAIN="$NAME.xctoolchain";
else
    INSTALL_LOC="$HOME/.swiftenv/versions";
    TOOLCHAIN=$NAME;
fi

if [ -d "$INSTALL_LOC/$TOOLCHAIN" ]; 
then
    echo "⬇️  Downloaded"
else
    COMPRESSED="$NAME-$OS.tar";

    echo "⬇️  Downloading"

    curl -LO swift.qutheory.io/binaries/$VERSION/$COMPRESSED;

    echo "🔧  Untarring"
    tar -xf $COMPRESSED;

    rm $COMPRESSED;

    echo "🚀  Installing";

    mkdir -p $INSTALL_LOC 2>/dev/null;
    mv $TOOLCHAIN $INSTALL_LOC 2>/dev/null;

    if [ $? -ne 0 ]; 
    then
        echo "🔒  Sudo required";
        sudo mkdir -p $INSTALL_LOC;
        sudo rm -rf $TOOLCHAIN/$INSTALL_LOC;
        sudo mv $TOOLCHAIN $INSTALL_LOC;
    fi
fi

swiftenv global $NAME
SWIFTV=`swift --version`;

if [[ $SWIFTV == *$SWIFTV_EXPECTED* ]];
then
    echo "✅  Done";
    if [[ $OS == "macos" ]];
    then
        echo "Make sure to change your Xcode > Toolchains to";
        echo "Swift Development Snapshot 2016-$VERSION (qutheory)";
    fi
else
    echo "❌  Something went wrong.";
    echo "Unexpected Swift version returned by";
    echo "    swift --version";
    echo "Expected to contain: $SWIFTV_EXPECTED";
fi
