#!/bin/sh

UNAME=`uname`;
VERSION="07-20"

if [[ $UNAME == "Darwin" ]];
then
    OS="macos";
    SWIFTV_EXPECTED="888ff1ae99";
else
    if [[ $UNAME == "Linux" ]];
    then
        SWIFTV_EXPECTED="55bf02ec04";
        UBUNTU_RELEASE=`lsb_release -a`;
        if [[ $UBUNTU_RELEASE == *"15.10"* ]];
        then
            OS="ubuntu1510";
        else
            OS="ubuntu1404";
        fi
    else
        echo "Unsupported Operating System: $UNAME";
    fi
fi

echo "Swift 3 Installer ($VERSION)";

echo "🖥  Operating System: $OS";

COMPRESSED="swift-DEVELOPMENT-SNAPSHOT-2016-$VERSION-qutheory-$OS.tar";

echo "⬇️  Downloading"

curl -LO swift.qutheory.io/binaries/$VERSION/$COMPRESSED;

echo "🔧  Untarring"
tar -xf $COMPRESSED;

if [[ $OS == "macos" ]];
then
    INSTALL_LOC="/Library/Developer/Toolchains";
    TOOLCHAIN="swift-DEVELOPMENT-SNAPSHOT-2016-$VERSION-qutheory.xctoolchain";
else
    INSTALL_LOC="/usr/local/bin";
    TOOLCHAIN="swift-DEVELOPMENT-SNAPSHOT-2016-$VERSION-qutheory";
fi

echo "🚀  Installing";

sudo mkdir -p $INSTALL_LOC;
sudo rm -rf "$INSTALL_LOC/$TOOLCHAIN";
sudo mv $TOOLCHAIN $INSTALL_LOC;

if [[ $OS == "macos" ]];
then
    PROFILE=".bash_profile";
else
    PROFILE=".bashrc";
fi

echo "" >> ~/$PROFILE;
echo "# Swift 3 Development $VERSION (qutheory) Support" >> ~/$PROFILE;
echo "export PATH=$INSTALL_LOC/$TOOLCHAIN/usr/bin:\"{\$PATH}\"" >> ~/$PROFILE;

source ~/$PROFILE;

SWIFTV=`swift --version`;

if [[ $SWIFTV == *$SWIFTV_EXPECTED* ]];
then
    echo "✅  Done";
    echo "Make sure to change your Xcode > Toolchains to";
    echo "Swift Development Snapshot 2016-$VERSION (qutheory)";
else
    echo "❌  Something went wrong.";
    echo "";
    echo "Unexpected Swift version returned by";
    echo "swift --version";
    echo "Expected: $SWIFTV_EXPECTED";
fi
