#!/bin/sh

UNAME=`uname`;
VERSION="07-20"

if [[ $UNAME == "Darwin" ]];
then
    OS="macos";
    SWIFTV_EXPECTED="888ff1ae99";
else
    if [[ $UNAME == "Linux" ]];
    then
        SWIFTV_EXPECTED="55bf02ec04";
        UBUNTU_RELEASE=`lsb_release -a 2>/dev/null`;
        if [[ $UBUNTU_RELEASE == *"15.10"* ]];
        then
            OS="ubuntu1510";
        else
            OS="ubuntu1404";
        fi
    else
        echo "Unsupported Operating System: $UNAME";
    fi
fi

echo "Swift 3 Installer ($VERSION)";

echo "🖥  Operating System: $OS";

if [[ $OS == "macos" ]];
then
    INSTALL_LOC="/Library/Developer/Toolchains";
    TOOLCHAIN="swift-DEVELOPMENT-SNAPSHOT-2016-$VERSION-qutheory.xctoolchain";
else
    INSTALL_LOC="/usr/local/bin";
    TOOLCHAIN="swift-DEVELOPMENT-SNAPSHOT-2016-$VERSION-qutheory";
fi

if [ -d "$INSTALL_LOC/$TOOLCHAIN" ]; 
then
    echo "⬇️  Downloaded"
else
    COMPRESSED="swift-DEVELOPMENT-SNAPSHOT-2016-$VERSION-qutheory-$OS.tar";

    echo "⬇️  Downloading"

    curl -LO swift.qutheory.io/binaries/$VERSION/$COMPRESSED;

    echo "🔧  Untarring"
    tar -xf $COMPRESSED;

    rm $COMPRESSED;

    if [[ $TRAVIS ]];
    then
        echo "Travis detected.";
        mv $TOOLCHAIN swift;

        INSTALL_LOC=$HOME;
        TOOLCHAIN="swift";
    fi

    echo "🚀  Installing";

    sudo mkdir -p $INSTALL_LOC;
    sudo rm -rf "$INSTALL_LOC/$TOOLCHAIN";
    sudo mv $TOOLCHAIN $INSTALL_LOC;
fi

if [[ $OS == "macos" ]];
then
    PROFILE=".bash_profile";
else
    PROFILE=".bashrc";
fi

LOADER=".swift-version-loader"
VFILE=".swift-version"

rm ~/$LOADER 2> /dev/null
echo "VERSION=\`cat ~/$VFILE | tr -d '[[:space:]]'\`" >> ~/$LOADER;
echo "" >> ~/$LOADER;
if [[ $OS == "macos" ]];
then
    echo "export PATH=$INSTALL_LOC/\$VERSION.xctoolchain/usr/bin:\"\$PATH\"" >> ~/$LOADER;
else
    echo "export PATH=$INSTALL_LOC/\$VERSION/usr/bin:\"\$PATH\"" >> ~/$LOADER;
fi

rm ~/$VFILE 2> /dev/null
echo "swift-DEVELOPMENT-SNAPSHOT-2016-$VERSION-qutheory" >> ~/$VFILE

if [[ $TRAVIS ]];
then
    PROFILE=".bashrc";
else
    if [[ `cat ~/$PROFILE` == *"source ~/$LOADER"* ]];
    then
        echo "⚠️  Open a new terminal tab or run";
        echo "    source ~/$PROFILE";
    else
        read -r -p "Add Swift loader to your ~/$PROFILE for Terminal access? [y/N] " response;
        if [[ $response =~ ^(yes|y|Y|YES)$ ]];
        then
            echo "" >> ~/$PROFILE;
            echo "# Swift 3 Development Version Loader" >> ~/$PROFILE;
            echo "source ~/$LOADER" >> ~/$PROFILE;

            echo "⚠️  Now open a new terminal tab or run";
            echo "    source ~/$PROFILE";
        else
            echo "⚠️  Add the following line to your ~/$PROFILE";
            echo "    source ~/$LOADER";
        fi
    fi
fi

PROF_CONTENTS=`cat ~/$PROFILE`
if [[ $PROF_CONTENTS == *"swiftenv"* ]];
then
    echo "⚠️  Your ~/$PROFILE contains references to swiftenv.";
    echo "This may interfere. Try commenting swiftenv out if you have issues."
fi

if [[ $PROF_CONTENTS == *".xctoolchain"* ]];
then
    echo "⚠️  Your ~/$PROFILE contains references to other Swift snapshots.";
    echo "This may interfere. Try commenting these out if you have issues."
fi

export PATH=$INSTALL_LOC/$TOOLCHAIN/usr/bin:"{$PATH}";

SWIFTV=`swift --version`;

if [[ $SWIFTV == *$SWIFTV_EXPECTED* ]];
then
    echo "✅  Done";
    if [[ $OS == "macos" ]];
    then
        echo "Make sure to change your Xcode > Toolchains to";
        echo "Swift Development Snapshot 2016-$VERSION (qutheory)";
    fi
else
    echo "❌  Something went wrong.";
    echo "Unexpected Swift version returned by";
    echo "    swift --version";
    echo "Expected to contain: $SWIFTV_EXPECTED";
fi
