#!/usr/bin/env bash

echo "Swift 3 Heroku Installer";

# Determine version
VERSION_FILE=".swift-version"
if [ ! -f $VERSION ]; 
then
    echo "No .swift-version file found."
    exit 1
fi
VERSION=`cat $VERSION_FILE | tr -d '[[:space:]]'`

echo "🔢  Version: $VERSION";

# Determine OS
UBUNTU_RELEASE=`lsb_release -a 2>/dev/null`;
if [[ $UBUNTU_RELEASE == *"15.10"* ]];
then
    OS="ubuntu1510";
else
    OS="ubuntu1404";
fi
echo "🖥  Operating System: $OS";

# Install Swiftenv
git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv 1>/dev/null
export SWIFTENV_ROOT="$HOME/.swiftenv"
export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"

INSTALL_LOC="$HOME/.swiftenv/versions";
TOOLCHAIN="swift-$VERSION";

echo "⬇️  Downloading";
COMPRESSED="$OS.tar";
curl -LO swift.qutheory.io/binaries/$VERSION/$COMPRESSED;

TAIL=`tail $COMPRESSED`;
if [[ $TAIL == *"</html>"* ]];
then
    echo "❓  Swift version not found, trying Swiftenv.";
    swiftenv install $VERSION;
else
    echo "🔧  Untarring"
    tar -xf $COMPRESSED;
    rm $COMPRESSED;

    echo "🚀  Installing";
    mkdir -p $INSTALL_LOC 2>/dev/null;
    mv $TOOLCHAIN $INSTALL_LOC 2>/dev/null;
    if [ $? -ne 0 ]; 
    then
        echo "🔒  Sudo required";
        sudo mkdir -p $INSTALL_LOC;
        sudo rm -rf $TOOLCHAIN/$INSTALL_LOC;
        sudo mv $TOOLCHAIN $INSTALL_LOC;
    fi

    # Prepare Swiftenv
    swiftenv rehash
    swiftenv global $TOOLCHAIN
fi

echo "✅  Done";
