#!/usr/bin/env bash

echo "Swift 3 Heroku Installer";

# Determine version
VERSION_FILE=".swift-version"
if [ ! -f $VERSION ]; 
then
    echo "No .swift-version file found."
    exit 1
fi
VERSION=`cat $VERSION_FILE | tr -d '[[:space:]]'`
echo "🔢  Version: $VERSION";

# Determine OS
UBUNTU_RELEASE=`lsb_release -a 2>/dev/null`;
if [[ $UBUNTU_RELEASE == *"15.10"* ]];
then
    OS="ubuntu1510";
else
    OS="ubuntu1404";
fi
echo "🖥  Operating System: $OS";


echo "📦 Installing Swiftenv"
git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv
export SWIFTENV_ROOT="$HOME/.swiftenv"
export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"

# echo "📚 Installing Dependencies"

echo "🐦 Installing Swift";
swiftenv install $VERSION;

echo "✅  Done";
