#!/usr/bin/env bash

echo "Swift 3 Quick Installer";

# Determine OS
UNAME=`uname`;
if [[ $UNAME == "Linux" ]];
then
    UBUNTU_RELEASE=`lsb_release -a 2>/dev/null`;
    if [[ $UBUNTU_RELEASE == *"14.04"* ]];
    then
        OS="ubuntu1404";
        TC="swift-3.0.1-RELEASE-ubuntu14.04"
    elif [[ $UBUNTU_RELEASE == *"15.10"* ]];
    then
        OS="ubuntu1510";
        TC="swift-3.0.1-RELEASE-ubuntu15.10"
    else
        OS="ubuntu1604";
        TC="swift-3.0.1-RELEASE-ubuntu16.04"
    fi
else
    echo "❌  Unsupported Operating System: $UNAME";
    exit 1;
fi

echo "🖥  Operating System: $OS";

echo "📦  Installing Dependencies"
echo "🔒  Sudo required";
sudo apt-get update
sudo apt-get -yq install clang libicu-dev git wget

echo "⬇️  Downloading"
wget https://swift.org/builds/swift-3.0.1-release/$OS/swift-3.0.1-RELEASE/$TC.tar.gz

echo "🔧  Untarring"
tar zxf $TC.tar.gz
rm -rf $TC.tar.gz

echo "🚀  Installing";
echo "🔒  Sudo required";
sudo mv $TC /swift-3.0.1

echo "export PATH=/swift-3.0.1/usr/bin:\"\${PATH}\"" >> ~/.bashrc
exec bash

echo "✅  Done";