#!/usr/bin/env bash

VERSION="3.0.1"
echo "Swift $VERSION Quick Installer";

# Determine OS
UNAME=`uname`;
if [[ $UNAME == "Linux" ]];
then
    UBUNTU_RELEASE=`lsb_release -a 2>/dev/null`;
    if [[ $UBUNTU_RELEASE == *"14.04"* ]];
    then
        OS="ubuntu1404";
        TC="swift-$VERSION-RELEASE-ubuntu14.04"
    elif [[ $UBUNTU_RELEASE == *"15.10"* ]];
    then
        OS="ubuntu1510";
        TC="swift-$VERSION-RELEASE-ubuntu15.10"
    else
        OS="ubuntu1604";
        TC="swift-$VERSION-RELEASE-ubuntu16.04"
    fi
else
    echo "❌  Unsupported Operating System: $UNAME";
    exit 1;
fi

echo "🖥  Operating System: $OS";

echo "📦  Installing Dependencies"
echo "🔒  Sudo required";
sudo apt-get -yq install clang libicu-dev git wget

echo "⬇️  Downloading"
wget https://swift.org/builds/swift-$VERSION-release/$OS/swift-$VERSION-RELEASE/$TC.tar.gz

echo "🔧  Untarring"
tar zxf $TC.tar.gz
rm -rf $TC.tar.gz

echo "🚀  Installing";
echo "🔒  Sudo required";
sudo mv $TC /swift-$VERSION

echo "export PATH=/swift-$VERSION/usr/bin:\"\${PATH}\"" >> ~/.bashrc
source ~/.bashrc

echo "✅  Done";